version: '3.1'

services :
  postgres:
    container_name:  postgres
    image:  postgres:latest
    environment:
      -  POSTGRES_DB=postgres
      -  POSTGRES_USER=viraset
      -  POSTGRES_PASSWORD=12345
    networks:
      -  default
    ports:
      -  "5432:5432"
    restart: always
    volumes: 
      -  postgres_data:/var/lib/postgresql/data
      
      
      
  app:
    build:  .
    command:  sh -c "python manage.py migrate && gunicorn A.wsgi -b 0.0.0.0:8000"
    container_name:  app
    volumes:
      -  .:/code/
    depends_on:
      -  postgres
    expose:
      -  "8000"
    networks:
      -  default
    restart:  always
    
    
  nginx:
    container_name:  nginx
    command: nginx -g 'daemon off;'
    depends_on:
      -  app
    image: nginx:latest
    networks:
      -  default
    ports:
      -  "80:80"
    restart: always
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:


